### ISSUE TITLE
MongooseError

### ISSUE THREAD

**Issue by dominikpflegerl** [MrDemonWolf/share#248]
# 🐞 bug report

### Affected Package

 The issue is caused by package **mongoose**

### Description

 First try to install it. I installed npm on my Windows 10 machine and also on WSL (Debian). After npm install I tried to start it with "npm start" and both times I got the same error:

## 🔥 Exception or Error
<pre><code>
C:\Users\Dominik\Desktop\Tools\share\node_modules\mongoose\lib\connection.js:579
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (C:\Users\Dominik\Desktop\Tools\share\node_modules\mongoose\lib\error\mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (C:\Users\Dominik\Desktop\Tools\share\node_modules\mongoose\lib\connection.js:579:11)
    at Mongoose.connect (C:\Users\Dominik\Desktop\Tools\share\node_modules\mongoose\lib\index.js:333:15)
    at Object.<anonymous> (C:\Users\Dominik\Desktop\Tools\share\src\index.js:43:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! share@4.2.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the share@4.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dominik\AppData\Roaming\npm-cache\_logs\2020-08-31T18_29_19_554Z-debug.log

</code></pre>

## 🌍  Your Environment

**NodeJS Version:**
<pre><code>

6.14.6

</code></pre>

**Anything else relevant?**

**Comment by nathanhenniges** [comment]
This app requires you to have a MongoDB running.  And setting it in `.env`
