### ISSUE TITLE
[4.0] Does not start

### ISSUE THREAD

**Issue by Loneystar** [MrDemonWolf/share#78]
npm start

> share-mrdemonwolf-me@4.0.0 start /home/share
> node src/index.js

/home/share/src/index.js:91
passport.use(User.createStrategy());
                  ^

TypeError: User.createStrategy is not a function
    at Object.<anonymous> (/home/share/src/index.js:91:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by nathanhenniges** [comment]
Already know 4.0 has issues.  It's unreleased for this reason.  Thanks for reporting this.  Please use version 3.1.2 as it's stable you can get it [here](https://github.com/MrDemonWolf/share/releases/tag/3.1.2).
